name: Close issue
# 传入的参数：
# issue number
# status completed not_planned
on:
  repository_dispatch:
    types: [closeissue]

permissions:
  contents: write

jobs:
  publishVpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EventIssue2Json repository
        uses: actions/checkout@v4
        with:
          repository: Sonic853/EventIssue2Json
          path: EventIssue2Json

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Install deno.json
        working-directory: EventIssue2Json
        run: |
          deno install

      - name: Output issue to Deno script
        run: |
          deno run --allow-net --allow-read --allow-write --allow-env --allow-ffi ./EventIssue2Json/closeissue.ts --owner=${{ github.event.client_payload.owner }} --repo=${{ github.event.client_payload.repo }} --issue=${{ github.event.client_payload.issue }} --status=${{ github.event.client_payload.status }} --token=${{ secrets.PAT }}
