name: Issue to Json
on:
  issues:
    types: 
      - labeled

permissions:
  contents: write

env:
  havefaild: 'false'

jobs:
  Issue2Json:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue has a specific label
        id: check-label
        run: |
          if [[ "${{ github.event.label.name }}" != "approve" ]]; then
            echo "The label does not match. Skipping script."
            echo "havefaild=true" >> $GITHUB_ENV
          fi
    
      - name: Checkout repository
        if: env.havefaild == 'false'
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
    
      - name: Checkout EventIssue2Json repository
        if: env.havefaild == 'false'
        uses: actions/checkout@v4
        with:
          repository: Sonic853/EventIssue2Json
          path: EventIssue2Json

      - name: Install Deno
        if: env.havefaild == 'false'
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Install deno.json
        if: env.havefaild == 'false'
        working-directory: EventIssue2Json
        run: |
          deno install

      - name: Output issue to Deno script
        if: env.havefaild == 'false'
        working-directory: ${{ github.event.repository.name }}
        run: |
          deno run --allow-net --allow-read --allow-write --allow-env --allow-ffi ../EventIssue2Json/issue2json.ts --owner=${{ github.event.repository.owner.login }} --repo=${{ github.event.repository.name }} --issue=${{ github.event.issue.number }} --token=${{ secrets.PAT }}

      - name: Check for changes and commit in ${{ github.event.repository.name }}
        if: env.havefaild == 'false'
        working-directory: ${{ github.event.repository.name }}
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions[bot]@users.noreply.github.com
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected"
            git add .
            git commit -m "Add Event files from ${{ github.event.issue.user.login }}'s issue close #${{ github.event.issue.number }}"
            git push
          else
            echo "No changes today"
            echo "havefaild=true" >> $GITHUB_ENV
          fi

      - name: Close issue
        if: env.havefaild == 'false'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          event-type: closeissue
          client-payload: '{"owner": "${{ github.event.repository.owner.login }}", "repo": "${{ github.event.repository.name }}", "issue": "${{ github.event.issue.number }}", "status": "completed"}'

      - name: Static page
        if: env.havefaild == 'false'
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: static
